# docs: https://github.com/docker-library/docs/blob/master/rethinkdb/README.md
# image: https://hub.docker.com/_/rethinkdb

version: "3.9"
services:
  rethinkdb:
    image: "rethinkdb:2.4.2"
    ports:
      - "8081:8080"
      - "28015:28015"
    # https://docs.docker.com/engine/reference/builder/#healthcheck
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 10s
    command:
      - /bin/bash
      - -c
      - |
        rethinkdb create --initial-password admin.,13
        rethinkdb --bind all
    volumes:
      - ~/container-volumes/rethinkdb-demo/data:/data
  fastapi:
    image: "rethinkdb-fastapi:latest"
    environment:
      RETHINKDB_USER: admin
      RETHINKDB_PASSWORD: admin.,13
      RETHINKDB_HOST: rethinkdb
    ports:
      - "8080:80"
    depends_on:
      rethinkdb:
        condition: service_healthy